version: '3'

services:
  master:
    build: ./master
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: community
      MYSQL_DATABASE: community
    ports:
      - "33306:3306"
    volumes:
      - ./master/config/my.cnf:/etc/mysql/my.cnf
      - master_data:/var/lib/mysql
    networks:
      - community-net

  slave:
    build : ./slave
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: community
      MYSQL_DATABASE: community
    ports:
      - "33307:3306"
    volumes:
      - ./slave/config/my.cnf:/etc/mysql/my.cnf
      - slave_data:/var/lib/mysql
    depends_on:
      - master
    networks:
      - community-net

volumes:
  master_data:
  slave_data:

networks:
  community-net:
    driver: bridge
    external: true
    name: master_community-net
